name: CI/CD Pipeline

on:
  push:
    branches:
      - Deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Log in to Amazon ECR
      env:
        AWS_REGION: ap-southeast-1
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image to ECR
      run: |
        docker build -t my-app ./src
        docker tag my-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/my-app-repo:latest
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/my-app-repo:latest
    

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production

    steps:
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1  

    - name: Deploy to Fargate
      run: |
        # Register ECS Task Definition
        aws ecs register-task-definition \
          --family my-app-task \
          --network-mode awsvpc \
          --requires-compatibilities FARGATE \
          --cpu "256" \
          --memory "512" \
          --execution-role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecs-execution-role \
          --container-definitions '[
            {
              "name": "my-app-container",
              "image": "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/my-app-repo:latest",
              "memory": 512,
              "cpu": 256,
              "essential": true,
              "portMappings": [
                {
                  "containerPort": 80,
                  "hostPort": 80
                }
              ]
            }
          ]'

        # Run ECS Task on Fargate
        aws ecs update-service \
          --cluster my-ecs-cluster \
          --service my-app-service \
          --task-definition my-app-task \
          --desired-count 1 \
          --network-configuration "awsvpcConfiguration={subnets=[subnet-0d7d6301178ce8c7f],assignPublicIp=ENABLED}" 